version: "3"
services:
  yxi-api:
    image: keller0/yxi-api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8090:8090"
    volumes:
      - "/var/log/yxi:/var/log/yxi"
    networks:
      - webnet
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - "api-db:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  elasticsearch:
    image: elasticsearch
    volumes:
      - "es-search-db:/usr/share/elasticsearch/data"

  kibana:
    image: kibana
    ports:
      - 5601:5601

networks:
  webnet:

volumes:
  api-db:
  es-search-db:
