version: "3"
services:
  yxi-api:
    image: keller0/yxi-api
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - "api-log:/var/log/yxi"
    networks:
      - webnet
  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    volumes:
      - "api-db:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  elasticsearch:
    image: elasticsearch
    volumes:
      - "es-search-db:/usr/share/elasticsearch/data"

  kibana:
    image: kibana
    ports:
      - 5601:5601

  nginx:
    image: nginx
    deploy:
      replicas: 1
    ports:
      - "9090:80"
    volumes:
      - "./config/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "nginx-log:/var/log/nginx/log"
    networks:
      - webnet

networks:
  webnet:

volumes:
  api-db:
  es-search-db:
  api-log:
  nginx-log: