filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/*.access*"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/*.error*"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"


